import {
  faVrCardboard,
  faBrain,
  faMicrochip,
  faClipboard,
  faCrown,
  faFeatherAlt,
  faChalkboardTeacher,
  faLaugh,
  faUserFriends,
  faDonate,
  faChartLine,
  faAward,
  faPlayCircle,
  faAddressCard,
  faArrowRight,
  faCalendarCheck,
  faMoneyCheckAlt,
  faHeadset,
  faPaste,
  faTasks,
  faUsers,
  faUserSecret,
  faEnvelope,
  faHome,
  faMap,
  faPhone,
} from "@fortawesome/free-solid-svg-icons";
import {
  faHive,
  faFacebook,
  faInstagram,
  faLinkedinIn,
  faTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

export const FONTAWESOMEICON = {
  iconVrCardboard: faVrCardboard,
  iconBrain: faBrain,
  iconMicrochip: faMicrochip,
  iconClipboard: faClipboard,
  iconCrown: faCrown,
  iconFeather: faFeatherAlt,
  iconChalkboardTeacher: faChalkboardTeacher,
  iconLaugh: faLaugh,
  iconUserFriends: faUserFriends,
  iconDonate: faDonate,
  iconChartLine: faChartLine,
  iconAward: faAward,
  iconPlayCircle: faPlayCircle,
  iconHive: faHive,
  iconAddressCard: faAddressCard,
  iconArrowRight: faArrowRight,
  iconCalenderCheck: faCalendarCheck,
  iconMoneyCheckAlt: faMoneyCheckAlt,
  iconHeadset: faHeadset,
  iconPaste: faPaste,
  iconTasks: faTasks,
  iconUsers: faUsers,
  iconSecret: faUserSecret,
  iconEnvelope: faEnvelope,
  iconHome: faHome,
  iconMap: faMap,
  iconPhone: faPhone,
  iconFacebook: faFacebook,
  iconInstagram: faInstagram,
  iconLinkedin: faLinkedinIn,
  iconTwitter: faTwitter,
  iconYoutube: faYoutube,
};
